#!/usr/bin/env bash
# Synchronise the test-fixture entries in .github/dependabot.yml.
#
# Usage:
#   scripts/sync-dependabot-config.sh          # update dependabot.yml in place
#   scripts/sync-dependabot-config.sh --check  # exit non-zero if out of date
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEPENDABOT_YML="$REPO_ROOT/.github/dependabot.yml"
BEGIN_MARKER="# ── BEGIN GENERATED: test fixture suppressions"
END_MARKER="# ── END GENERATED: test fixture suppressions"

check_mode=false
if [[ "${1:-}" == "--check" ]]; then
  check_mode=true
fi

# ── Manifest → ecosystem mapping ─────────────────────────────────────
# Dependabot ecosystem names:
#   pom.xml                → maven
#   build.gradle(.kts)     → gradle
#   requirements.txt       → pip
#   pyproject.toml         → pip, uv  (both scanners pick it up)
#   go.mod                 → gomod
#   Cargo.toml             → cargo
#   package.json           → npm      (covers npm/yarn/pnpm/bun)
#   Gemfile                → bundler

declare -A MANIFEST_ECOSYSTEMS=(
  ["pom.xml"]="maven"
  ["build.gradle"]="gradle"
  ["build.gradle.kts"]="gradle"
  ["requirements.txt"]="pip"
  ["pyproject.toml"]="pip uv"
  ["go.mod"]="gomod"
  ["Cargo.toml"]="cargo"
  ["package.json"]="npm"
  ["Gemfile"]="bundler"
)

MANIFEST_NAMES=$(IFS='|'; echo "${!MANIFEST_ECOSYSTEMS[*]}" | tr ' ' '\n' | sort -u | tr '\n' '|'; echo)
MANIFEST_NAMES="${MANIFEST_NAMES%|}"

# ── Discover test fixture directories ─────────────────────────────────
declare -A ECOSYSTEM_DIRS

while IFS= read -r manifest_path; do
  dir="$(dirname "$manifest_path")"
  filename="$(basename "$manifest_path")"
  ecosystems="${MANIFEST_ECOSYSTEMS[$filename]}"

  for eco in $ecosystems; do
    existing="${ECOSYSTEM_DIRS[$eco]:-}"
    if [[ -z "$existing" ]]; then
      ECOSYSTEM_DIRS[$eco]="$dir"
    else
      ECOSYSTEM_DIRS[$eco]="$existing"$'\n'"$dir"
    fi
  done
done < <(
  find "$REPO_ROOT/test" -type f \( \
    -name "pom.xml" -o \
    -name "build.gradle" -o \
    -name "build.gradle.kts" -o \
    -name "requirements.txt" -o \
    -name "pyproject.toml" -o \
    -name "go.mod" -o \
    -name "Cargo.toml" -o \
    -name "package.json" -o \
    -name "Gemfile" \
  \) -not -path "*/node_modules/*" \
    -not -path "*/.gradle/*" \
    -not -path "*/build/*" \
    -not -path "*/target/*" | sort
)

# ── Generate YAML ────────────────────────────────────────────────────
generate_yaml() {
  echo "$BEGIN_MARKER"
  echo "  # Auto-generated by scripts/sync-dependabot-config.sh."
  echo "  # Do not edit manually — run the script to update."

  for eco in $(echo "${!ECOSYSTEM_DIRS[@]}" | tr ' ' '\n' | sort); do
    dirs="${ECOSYSTEM_DIRS[$eco]}"
    sorted_dirs=$(echo "$dirs" | sort -u)

    echo "  - package-ecosystem: \"$eco\""
    echo "    directories:"
    while IFS= read -r dir; do
      rel="/${dir#"$REPO_ROOT/"}"
      echo "      - \"$rel\""
    done <<< "$sorted_dirs"
    echo "    schedule:"
    echo "      interval: \"monthly\""
    echo "    open-pull-requests-limit: 0"
    echo "    labels: []"
    echo "    ignore:"
    echo "      - dependency-name: \"*\""
  done

  echo "  $END_MARKER"
}

generated=$(generate_yaml)

# ── Check or update ──────────────────────────────────────────────────
if ! grep -qF "$BEGIN_MARKER" "$DEPENDABOT_YML"; then
  if $check_mode; then
    echo "ERROR: $DEPENDABOT_YML is missing the generated section marker."
    echo "Run 'scripts/sync-dependabot-config.sh' to add it."
    exit 1
  fi
  # Append the generated section
  {
    echo ""
    echo "$generated"
  } >> "$DEPENDABOT_YML"
  echo "Added test fixture entries to $DEPENDABOT_YML"
  exit 0
fi

# Extract the file before and after the markers
before=$(sed -n "1,/^${BEGIN_MARKER}/{ /^${BEGIN_MARKER}/d; p; }" "$DEPENDABOT_YML")
tmpfile=$(mktemp)
trap 'rm -f "$tmpfile"' EXIT
printf '%s\n%s\n' "$before" "$generated" > "$tmpfile"

if $check_mode; then
  if diff -q "$DEPENDABOT_YML" "$tmpfile" > /dev/null 2>&1; then
    echo "dependabot.yml is up to date."
    exit 0
  else
    echo "ERROR: dependabot.yml is out of date."
    echo ""
    diff --unified "$DEPENDABOT_YML" "$tmpfile" || true
    echo ""
    echo "Run 'scripts/sync-dependabot-config.sh' to fix."
    exit 1
  fi
fi

cp "$tmpfile" "$DEPENDABOT_YML"
echo "Updated test fixture entries in $DEPENDABOT_YML"
